name: Upstream Kernel from OpenELA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily (00:00 UTC)

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: MoeKernel/checkout@v4.1.6

    - name: Install dependencies
      run: |
        sudo apt install git python3 python3-pip -y
  
    - name: Clone Repo cli
      uses: MoeKernel/github-repo-action@v3.1
      with:
        owner: 'MoeKernel'
        branch: 'main'
        repository: 'cli'

    - name: Clone Repo Kernel
      uses: MoeKernel/github-repo-action@v3.1
      with:
        depth: 1
        branch: 'fourteen'
        owner: 'MoeKernel'
        repository: 'android_kernel_xiaomi_ginkgo'

    - name: Install Library Pip
      run: |
        pip install load_dotenv

    - name: Set up GitHub Token
      working-directory: ./android_kernel_xiaomi_ginkgo
      run: |
        echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env

    - name: Move Scripts
      working-directory: ./cli
      run: |
        cp upstream.py ../android_kernel_xiaomi_ginkgo

    - name: Execute Upstream
      working-directory: ./android_kernel_xiaomi_ginkgo
      run: |
        python upstream.py
