name: Upstream Kernel from OpenELA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily (00:00 UTC)

jobs:
  upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: MoeKernel/checkout@v4.1.6

    - name: Install dependencies
      run: |
        sudo apt install git python3 python3-pip -y
  
    - name: Clone Repo Scripts
      uses: MoeKernel/github-repo-action@v3.1
      with:
        owner: 'MoeKernel'
        branch: 'main'
        repository: 'cli'

    - name: Install Requests Library
      run: |
        pip install requests load_dotenv

    - name: Execute Upstream
      working-directory: ./cli
      run: |
        python upstream.py
