name: Upstream Kernel from OpenELA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily (00:00 UTC)

jobs:
  upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: MoeKernel/checkout@v4.1.6

    - name: Install dependencies
      run: |
        sudo apt install git python3 -y
        
    - name: Clone Repo Kernel
      run: |
        git clone https://github.com/MoeKernel/android_kernel_xiaomi_ginkgo
        pwd
        ls android_kernel_xiaomi_ginkgo
        
    - name: Execute upstream script
      run: |
        pwd
        python .github/ci/upstream.py
