name: Build G84 5G (NOKSU/Fourteen)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        device: [g84]

    steps:
      - name: Clone Repo Kernel
        uses: MoeKernel/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'non-ksu'
          owner: 'MoeKernel'
          repository: 'android_kernel_motorola_bangkk'

      - name: Run build
        working-directory: ./android_kernel_motorola_bangkk
        run: |
          ./build.sh
