name: Build Kernel (Ginkgo/Willow) (with KSU)

on:
  workflow_dispatch

env:
  ZIPNAME: MoeKernel-$(date '+%Y%m%d-%H%M').zip
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Repo Kernel
        uses: whyakari/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'main'
          owner: 'whyakari'
          repository: 'android_kernel_xiaomi_ginkgo'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Clone Repo Scripts
        uses: whyakari/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'main'
          owner: 'whyakari'
          repository: 'scripts'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Move CI Build
        working-directory: scripts
        run: |
          chmod +x ksu_update.sh
          cp ksu_update.sh ci_build.py ../android_kernel_xiaomi_ginkgo

      - name: Github set Config Email and Name
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get -y --no-install-recommends install python3 python3-pip git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev bc binutils-dev ca-certificates clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev
      
      - name: Pip Install Packages
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          pip install Pyrogram TgCrypto

      - name: Compile Kernel Via Bot
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          python3 ci_build.py -t development # release
