name: Build Kernel (KSU)

on:
  workflow_dispatch

env:
  ZIPNAME: MoeKernel-$(date '+%Y%m%d-%H%M').zip
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo Kernel
        uses: MoeKernel/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'thirteen'
          owner: 'MoeKernel'
          repository: 'android_kernel_xiaomi_ginkgo'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Clone Repo Scripts
        uses: MoeKernel/github-repo-action@v3.1
        with:
          owner: 'MoeKernel'
          branch: 'ksu'
          repository: 'scripts'
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Move Scripts
        working-directory: ./scripts
        run: |
          chmod +x ksu_update.sh download_clang18.0.0.sh build_ci 
          cp build_ci download_clang18.0.0.sh build_count.txt ksu_update.sh ../android_kernel_xiaomi_ginkgo

      - name: Github Configs
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          git config --global user.email "moenyanuwu@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get -y --no-install-recommends install python3 python3-pip git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev bc binutils-dev ca-certificates clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

      - name: Compile Kernel CI
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          ./download_clang18.0.0.sh
          ./build_ci

      - name: Move CI Build count
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          cp build_count.txt ../scripts

      - name: Commit Update
        working-directory: ./scripts
        run: |
          git add build_count.txt
          git commit -m "update build count"
          git push origin ksu --force
