name: Build Test Go Cache

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore Go Cache
        id: go-cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Compile Hello World
        run: |
          go build -o hello hello.go

      - name: Simulate Cache
        run: |
          echo "Simulating cache..."
          if [ -f ~/go/pkg/mod/github.com ]; then
            echo "Cache found!"
          else
            echo "Cache not found!"
          fi

      - name: Cache Go Dependencies
        id: cache-go
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: CCache Create
        uses: MoeKernel/cache/save@v3
        with:
          path: /home/runner/.config/ccache
          key: ${{ github.os }}-ccache-test
