name: Build Kernel (KSU)

on:
  workflow_dispatch

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo Kernel
        uses: MoeKernel/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'fourteen'
          owner: 'MoeKernel'
          repository: 'android_kernel_xiaomi_ginkgo'

      - name: Clone Repo Scripts
        uses: MoeKernel/github-repo-action@v3.1
        with:
          owner: 'MoeKernel'
          branch: 'ksu'
          repository: 'scripts'

      - name: Move Scripts
        working-directory: ./scripts
        run: |
          chmod +x ksu_update.sh build_ci 
          cp build_ci build_count.txt ksu_update.sh ../android_kernel_xiaomi_ginkgo

      - name: Restore Cache
        uses: MoeKernel/cache@v3
        with:
          path: /home/runner/tc
          key: ${{ runner.os }}-tc
        id: tc-cache 

      - name: Github Configs
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get -y --no-install-recommends install python3 python3-pip git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev bc binutils-dev ca-certificates clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

      - name: Compile Kernel CI
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          ./build_ci

      - name: Move CI Build count
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          cp build_count.txt ../scripts

      - name: Commit Update
        working-directory: ./scripts
        run: |
          git add build_count.txt
          git commit -m "update build count"
          git push origin ksu --force
