name: Build Kernel (KSU/Dynamic/Fourteen)

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo Kernel
        uses: MoeKernel/github-repo-action@v3.1
        with:
          depth: 1
          branch: 'fourteen_dynamic'
          owner: 'MoeKernel'
          repository: 'android_kernel_xiaomi_ginkgo'

      - name: Clone Repo Scripts
        uses: MoeKernel/github-repo-action@v3.1
        with:
          owner: 'MoeKernel'
          branch: 'ksu_dynamic'
          repository: 'scripts'

      - name: Move Scripts
        working-directory: ./scripts
        run: |
          chmod +x ksu_update.sh bot.py
          cp bot.py build_count.txt ksu_update.sh ../android_kernel_xiaomi_ginkgo

      - name: Restore Cache
        uses: MoeKernel/cache@v3
        with:
          path: /home/runner/tc
          key: ${{ runner.os }}-tc
        id: tc-cache

      - name: Restore CCache
        uses: MoeKernel/cache@v3
        with:
          path: /home/runner/.config/ccache
          #key: ${{ runner.os }}-ccache
          key: ccache-${{ steps.ccache.outputs.cache-key }}

      - name: Github Configs
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          git config --global user.email "akariondev@gmail.com"
          git config --global user.name "ginkgo"
  
      - name: Install Dependencies
        run: |
         sudo apt-get update
         sudo apt-get -y --no-install-recommends install python3 python3-pip git make gcc bc bison flex libssl-dev ccache libelf-dev libncurses-dev bc binutils-dev ca-certificates clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

      - name: Pip Install Packages
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          pip install Pyrogram TgCrypto load_dotenv

      - name: Export Variables
        run: |
         echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
         echo "API_ID=${{ secrets.API_ID }}" >> .env
         echo "API_HASH=${{ secrets.API_HASH }}" >> .env
         echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

      - name: Ccache for MoeKernel
        id: ccache
        uses: MoeKernel/ccache-action@v1.2.13
        with:
          max-size: 5G
          #key: ${{ runner.os }}-ccache
          key: ccache-${{ github.run_id }}

      - name: Check Free Space
        run: |
          echo "Free space:"
          df -h

      - name: Check Free RAM
        run: |
          echo "Free RAM:"
          free -h

      - name: Compile Kernel CI
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          python3 bot.py -t dev # or release.

      - name: CCache Create
        uses: MoeKernel/cache/save@v3
        with:
          path: /home/runner/.config/ccache
          key: ${{ runner.os }}-ccache

      - name: Move CI Build
        working-directory: ./android_kernel_xiaomi_ginkgo
        run: |
          cp build_count.txt ../scripts

      - name: Commit Update
        working-directory: ./scripts
        run: |
          git config --global user.email "barryofc11@gmail.com"
          git config --global user.name "Akari"
          git remote set-url origin https://${{ secrets.TOKEN_GITHUB }}@github.com/MoeKernel/scripts.git

          git add build_count.txt
          git commit -m "update build count"
          git push origin ksu_dynamic -f
