name: Cache

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo Scripts
      uses: MoeKernel/github-repo-action@v3.1
      with:
        owner: 'MoeKernel'
        repository: 'scripts'
        branch: 'ksu'
        access-token: ${{ secrets.TOKEN_GITHUB }}

    - name: Export Variable TOKEN_GITHUB
      working-directory: ./scripts
      run: |
        echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env

    - name: Install Depends
      working-directory: ./scripts
      run: |
        pip install load_dotenv

    - name: Check for Clang Update
      id: check-update
      working-directory: ./scripts
      run: |
        python3 update.py
      continue-on-error: true

    - name: Download Clang
      if: steps.check-update.outcome == 'success'
      run: |
        chmod +x clang.sh
        ./clang.sh # download clang.

    - name: Download Clang
      working-directory: ./scripts
      run: |
        chmod +x clang.sh
        ./clang.sh

    - name: Setup GCC / GCC32 / Clang
      run: |
        TC_DIR="$HOME/tc/clang-19.0.0"
        GCC_64_DIR="$HOME/tc/aarch64-linux-android-14.0"
        GCC_32_DIR="$HOME/tc/arm-linux-androideabi-14.0"

        if ! [ -d "${GCC_64_DIR}" ]; then
            echo "gcc not found! Cloning to ${GCC_64_DIR}..."
            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu ${GCC_64_DIR}
        fi

        if ! [ -d "${GCC_32_DIR}" ]; then
            echo "gcc_32 not found! Cloning to ${GCC_32_DIR}..."
            git clone --depth=1 -b 14 https://github.com/ZyCromerZ/arm-zyc-linux-gnueabi ${GCC_32_DIR}
        fi

    - name: Cache Create
      id: tc-cache
      uses: MoeKernel/cache/save@v3
      with:
        path: /home/runner/tc
        key: ${{ runner.os }}-tc

    - name: Display cached directories
      run: |
        ls -R $HOME/tc/
