name: Test Workflow

on:
  workflow_dispatch

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo Scripts
        uses: MoeKernel/github-repo-action@v3.1
        with:
          owner: 'MoeKernel'
          branch: 'without-ksu'
          repository: 'scripts'

      - name: Update build_count.txt Test
        working-directory: ./scripts
        run: |
          echo 84 > build_count.txt

      - name: Commit Update
        working-directory: ./scripts
        run: |
          git config --global user.email "barryofc11@gmail.com"
          git config --global user.name "Akari"
          git remote set-url origin https://${{ secrets.TOKEN_GITHUB }}@github.com/MoeKernel/scripts.git

          git add build_count.txt
          git commit -m "update build count"
          git push origin without-ksu -f
