name: Build Test CCache

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Restore CCache Test
        id: ccache
        uses: MoeKernel/cache@v3
        with:
          path: /home/runner/.config/ccache
          key: ${{ github.os }}-ccache-test

      - name: Ccache for MoeKernel
        uses: MoeKernel/ccache-action@v1.2.13
        with:
          max-size: 5G
          key: ${{ github.os }}-ccache-test

      - name: Check Free Space
        run: |
          echo "Free space:"
          df -h

      - name: Check Free RAM
        run: |
          echo "Free RAM:"
          free -h

      - name: Create Test File
        run: |
          echo "This is a test file." > test.txt
          ccache test.txt

      - name: CCache Create
        uses: MoeKernel/cache/save@v3
        with:
          path: /home/runner/.config/ccache
          key: ${{ github.os }}-ccache-test
