name: Save Text File Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create random text file
        run: echo "$(openssl rand -base64 32)" > random.txt

      - name: Save cache
        uses: MoeKernel/cache@v3
        with:
          path: random.txt
          key: ${{ runner.os }}-text-file-cache

      - name: Save cache
        uses: MoeKernel/cache@v3
        with:
          path: random.txt
          key: ${{ runner.os }}-text-file-cache-v2

      - name: Display cache key
        run: |
          echo "Text file cache key: ${{ runner.os }}-text-file-cache"
