name: Build Test CCache

on:
  workflow_dispatch

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

jobs:
  build_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Restore CCache Test
        id: ccache
        uses: MoeKernel/cache@v3
        with:
          path: /home/runner/.config/ccache
          key: ${{ github.os }}-ccache-test

      - name: Ccache for MoeKernel
        uses: MoeKernel/ccache-action@v1.2.13
        with:
          max-size: 5G
          key: ${{ github.os }}-ccache-test

      - name: Check Free Space
        run: |
          printf "Free space:\n"
          df -h

      - name: Check Free RAM
        run: |
          printf "Free RAM:\n"
          free -h

      - name: Create Test File
        run: |
          wget https://gist.githubusercontent.com/whyakari/ecf9686abd8dc14380e5f7f4d262e91b/raw/6c489c6ab9016d0957d3cd0d3f30f57f499687f9/test.c
          cat test.c

      - name: Compile Test
        run: |
          ccache gcc -o test test.c

      - name: Simulate Cache
        run: |
          printf "Simulating cache...\n"
          if [ -d /home/runner/.config/ccache ]; then
            printf "Cache found!\n"
          else
            printf "Cache not found!\n"
          fi

      - name: Cleanup
        run: |
          rm -f test.c test
