name: Cache Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo Clang
        uses: MoeKernel/github-repo-action@v3.1
        with:
          owner: MoeKernel
          repository: clang
          branch: main
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Export Variables
        working-directory: ./clang
        run: |
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env

      - name: Install Depends
        working-directory: ./clang
        run: |
          pip install -r requirements.txt

      - name: Check Clang Update
        id: check-update
        working-directory: ./clang
        run: |
          python3 update.py
        continue-on-error: true

      - name: Download Clang
        if: steps.check-update.outcome == 'success'
        working-directory: ./clang
        run: |
          chmod +x clang.sh
          ./clang.sh

      - name: Create Release to GitHub.
        working-directory: ./clang
        run: |
          python3 create_release.py

      - name: Setup Clang
        run: |
          TC_DIR="$HOME/tc/clang-20.0.0"

      - name: Cache Create
        id: tc-toolchain_20
        uses: MoeKernel/cache/save@v3
        with:
          path: /home/runner/tc/clang-20.0.0
          key: ${{ runner.os }}-toolchain-20
