name: Update Kernel

on:
  schedule:
    - cron: '0 0 * * 0' 
    # Runs every Sunday at 00:00
  workflow_dispatch:

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Scripts Repo
      uses: MoeKernel/checkout@v4.1.6
            
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install python3 python3-pip git make bc ca-certificates git xz-utils

    - name: Install Requests Library
      run: |
        pip install requests load_dotenv

    - name: Clone Repo Scripts
      uses: MoeKernel/github-repo-action@v3.1
      with:
        owner: 'MoeKernel'
        branch: 'ksu'
        repository: 'scripts'

    - name: Set up GitHub Token
      run: |
        echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env

    - name: Github Configs
      working-directory: ./scripts
      run: |
        git config --global user.email "akariondev@gmail.com"
        git config --global user.name "ginkgo"
  
    - name: Run Update Script
      working-directory: ./scripts
      run: |
        python update_kernel.py
