name: Update Kernel

on:
  schedule:
    - cron: '0 0 * * 0' 
    # Executa a cada domingo às 00:00
  workflow_dispatch:

jobs:
  update_kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Scripts Repo
      uses: MoeKernel/checkout@v4.1.6
            
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install python3 python3-pip git make bc ca-certificates git xz-utils

    - name: Install Requests Library
      run: |
        pip install requests

    - name: Clone Repo Scripts
      uses: MoeKernel/github-repo-action@v3.1
      with:
        owner: 'MoeKernel'
        branch: 'ksu'
        repository: 'scripts'

    - name: Run Update Script
      working-directory: ./scripts
      run: |
        python cherry_pick_and_commit.py
